
"""
📰 AI News Digest Agent
Flow: Google News RSS → Gemini Summarizes → Send Email
Run: python3 agent.py
"""

import os
import smtplib
import feedparser
import google.generativeai as genai
from datetime import datetime
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from dotenv import load_dotenv

load_dotenv()

# ─── STEP 1: FETCH NEWS ──────────────────────────────────────────────────────

def fetch_google_news():
    topics = os.getenv("GOOGLE_NEWS_TOPICS", "technology,world news,AI").split(",")
    
    articles = []
    for topic in topics:
        url = f"https://news.google.com/rss/search?q={topic.strip().replace(' ', '+')}&hl=en-US&gl=US&ceid=US:en"
        feed = feedparser.parse(url)
        for entry in feed.entries[:3]:
            articles.append({
                "source": topic.strip(),
                "title": entry.title,
                "summary": entry.get("summary", "")[:300]
            })
        print(f"✅ Fetched {len(feed.entries[:3])} articles for '{topic.strip()}'")
    
    return articles

# ─── STEP 2: SUMMARIZE WITH GEMINI ───────────────────────────────────────────

def summarize_with_gemini(articles):
    genai.configure(api_key=os.getenv("GEMINI_API_KEY"))
    model = genai.GenerativeModel("gemini-2.5-flash")
    
    content = ""
    for a in articles:
        content += f"[{a['source']}] {a['title']}\n"
       
    
    prompt = f"""You are a sharp, friendly news editor. Below is today's headlines.

Create a morning news digest with:
1. **Top 3 Big Stories** - Most important news today (2-3 sentences each)
2. **Quick Hits** - 5 bullet points of other interesting stories
3. **Interesting Trend** - One pattern you notice across today's news

Keep it conversational, smart, under 400 words. No fluff.

---
{content}
"""
    
    response = model.generate_content(prompt)
    print("✅ Gemini summarized the news")
    return response.text

# ─── STEP 3: SEND EMAIL ──────────────────────────────────────────────────────

def send_email(summary):
    sender = os.getenv("GMAIL_ADDRESS")
    password = os.getenv("GMAIL_APP_PASSWORD")
    recipient = os.getenv("RECIPIENT_EMAIL", sender)
    date_str = datetime.now().strftime("%A, %B %d %Y")

    html_body = summary.replace("\n", "<br>")
    html = f"""
<!DOCTYPE html>
<html>
<head>
  <style>
    body {{ font-family: Georgia, serif; max-width: 620px; margin: 40px auto; color: #222; }}
    .header {{ background: #0f172a; color: white; padding: 24px 32px; border-radius: 12px 12px 0 0; }}
    .header h1 {{ margin: 0; font-size: 20px; }}
    .header p {{ margin: 4px 0 0; opacity: 0.6; font-size: 13px; }}
    .body {{ background: white; padding: 28px 32px; border-radius: 0 0 12px 12px; border: 1px solid #e8e8e8; line-height: 1.7; }}
    .footer {{ text-align: center; padding: 12px; font-size: 12px; color: #999; }}
  </style>
</head>
<body>
  <div class="header">
    <h1>📰 Your Morning News Digest</h1>
    <p>{date_str} · Powered by Gemini AI</p>
  </div>
  <div class="body">{html_body}</div>
  <div class="footer">Sources: Google News · Generated by your AI News Agent</div>
</body>
</html>
"""

    msg = MIMEMultipart("alternative")
    msg["Subject"] = f"📰 Morning Digest — {datetime.now().strftime('%b %d')}"
    msg["From"] = sender
    msg["To"] = recipient
    msg.attach(MIMEText(summary, "plain"))
    msg.attach(MIMEText(html, "html"))

    with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
        server.login(sender, password)
        server.sendmail(sender, recipient, msg.as_string())
    
    print(f"✅ Email sent to {recipient}")

# ─── RUN ─────────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    print("🚀 Starting News Digest Agent...\n")
    
    articles = fetch_google_news()
    summary = summarize_with_gemini(articles)
    send_email(summary)
    
    print("\n🎉 Done! Check your inbox.")
